apiVersion: v1
kind: Namespace
metadata:
  name: ns-vuthy-tourn-bba33c3e
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app.kubernetes.io/managed-by: argocd
    platform.devops/user-namespace: "true"
    platform.devops/user-id: "6fd1a56f-5544-4ee3-adeb-023b76"
    platform.devops/workspace-id: "ns-vuthy-tourn-bba33c3e"
