apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "api-gateway-1"
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/managed-by: argocd
    platform.devops/project-name: "api-gateway"
spec:
  project: "default"
  destination:
    server: https://kubernetes.default.svc
    namespace: "user-1"
  sources:
    - repoURL: "https://github.com/Vuthy-Tourn/platform-infra-testing"
      targetRevision: "main"
      path: "helm/app-template"
      helm:
        releaseName: "api-gateway"
        valueFiles:
          - $values/apps/1/1/api-gateway/values.yaml
    - repoURL: "git@github.com:Vuthy-Tourn/platform-gitops.git"
      targetRevision: "main"
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
