apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: user-1
helmGlobals:
  chartHome: ../../../../templates/charts
helmCharts:
  - name: app-template
    releaseName: api-gateway
    valuesFile: values.yaml
