apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ns-sorn-sophamarinet-c2332eff
resources:
  - namespace.yaml
helmGlobals:
  chartHome: ../../../../templates/charts
helmCharts:
  - name: app-template
    releaseName: flower
    valuesFile: values.yaml
