apiVersion: v1
kind: Namespace
metadata:
  name: ns-sorn-sophamarinet-c2332eff
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app.kubernetes.io/managed-by: argocd
    platform.devops/user-namespace: "true"
    platform.devops/user-id: "122d1924-4c05-41d4-878d-57293d"
    platform.devops/workspace-id: "ns-sorn-sophamarinet-c2332eff"
