apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: user-vuthy
resources:
  - namespace.yaml
helmGlobals:
  chartHome: ../../../../templates/charts
helmCharts:
  - name: app-template
    releaseName: workspace-stack
    valuesFile: values.yaml
