apiVersion: v1
kind: Namespace
metadata:
  name: user-vuthy
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app.kubernetes.io/managed-by: argocd
    platform.devops/user-namespace: "true"
    platform.devops/user-id: "vuthy"
    platform.devops/workspace-id: "vuthy-tourn-bba33c3e"
