apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "tui-test-088a88b5-0b05-4540-af95-988ae5"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/managed-by: argocd
    platform.devops/project-name: "tui-test"
spec:
  project: "default"
  destination:
    server: https://kubernetes.default.svc
    namespace: "ns-vuthy-tourn-f464566f"
  source:
    repoURL: "https://github.com/Vuthy-Tourn/platform-gitops"
    targetRevision: "main"
    path: "apps/ns-vuthy-tourn-f464566f/088a88b5-0b05-4540-af95-988ae5/tui-test"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  info:
    - name: templateRepo
      value: "https://github.com/Vuthy-Tourn/platform-infra-testing"
    - name: templateRevision
      value: "main"
    - name: templatePath
      value: "helm/app-template"
