apiVersion: v1
kind: Namespace
metadata:
  name: ns-vuthy-tourn-bba33c3e
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app.kubernetes.io/managed-by: argocd
    platform.devops/user-namespace: "true"
    platform.devops/user-id: "268ab5ff-ad99-45f9-b4d2-5ce49a"
    platform.devops/workspace-id: "ns-vuthy-tourn-bba33c3e"
