apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-api-gateway-sample-user
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/managed-by: argocd
    platform.devops/project-name: "api-gateway"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: user-sample-user
  sources:
    - repoURL: git@github.com:your-org/platform-infra-micro.git
      targetRevision: main
      path: helm/app-template
      helm:
        releaseName: api-gateway
        valueFiles:
          - $values/apps/sample-workspace/sample-user/api-gateway/values.yaml
    - repoURL: git@github.com:your-org/gitops-repo.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
