apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "microservices-37bf525a-8ed2-4c6a-8f0a-05a248"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/managed-by: argocd
    platform.devops/project-name: "microservices"
spec:
  project: "default"
  destination:
    server: https://kubernetes.default.svc
    namespace: "ns-chengdevith-f00120b6"
  source:
    repoURL: "https://github.com/Vuthy-Tourn/platform-gitops"
    targetRevision: "main"
    path: "apps/ns-chengdevith-f00120b6/37bf525a-8ed2-4c6a-8f0a-05a248/microservices"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  info:
    - name: templateRepo
      value: "https://github.com/Vuthy-Tourn/platform-infra-testing"
    - name: templateRevision
      value: "main"
    - name: templatePath
      value: "helm/app-template"
