apiVersion: v1
kind: ServiceAccount
metadata:
  name: config-server
  namespace: user-1
  labels:
    app.kubernetes.io/name: config-server
    app.kubernetes.io/managed-by: kustomize
    platform.devops/user-id: "1"
    platform.devops/project-name: "config-server"
    platform.devops/framework: "springboot-gradle"
    platform.devops/service-type: "internal"
imagePullSecrets:
  - name: registry-secret
