apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "workspace-stack-1"
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/managed-by: argocd
    platform.devops/project-name: "workspace-stack"
spec:
  project: "default"
  destination:
    server: https://kubernetes.default.svc
    namespace: "user-1"
  source:
    repoURL: "https://github.com/Vuthy-Tourn/platform-gitops"
    targetRevision: "main"
    path: "apps/1/1/workspace-stack"
    kustomize: {}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  info:
    - name: templateRepo
      value: "https://github.com/Vuthy-Tourn/platform-infra-testing"
    - name: templateRevision
      value: "main"
    - name: templatePath
      value: "helm/app-template"
