workspace:
  id: "ns-sorn-sophamarinet-5e2adcb5"
  userId: "28cdfd36-7ffe-4491-83f3-0e44be"
  namespace: "ns-sorn-sophamarinet-5e2adcb5"
  domain: "autonomous-istad.com"

imagePullSecrets:
  - name: "registry-secret"

defaults:
  replicaCount: 1
  image:
    pullPolicy: "IfNotPresent"
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 70
  nodeSelector: {}
  tolerations: []
  affinity: {}

services:
  - name: "config-server"
    framework: "springboot-gradle"
    serviceType: "internal"
    exposePublic: false
    primaryPublic: false
    syncWave: 0
    replicaCount: 1
    containerPort: 8888
    servicePort: 8888
    host: "config-server-808e64-5e2adcb5.autonomous-istad.com"
    image:
      repository: "goharbor-itp.anajak-khmer.site/microservices-deployment/28cdfd36-7ffe-4491-83f3-0e44be/simple-micro/config-server"
      tag: "20-e54233756237"
      pullPolicy: "IfNotPresent"
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    probes:
      mode: "http"
      startup:
        enabled: true
        path: "/actuator/health"
        initialDelaySeconds: 0
        periodSeconds: 5
        failureThreshold: 24
      readiness:
        enabled: true
        path: "/actuator/health/readiness"
        initialDelaySeconds: 10
        periodSeconds: 10
        failureThreshold: 3
      liveness:
        enabled: true
        path: "/actuator/health/liveness"
        initialDelaySeconds: 30
        periodSeconds: 15
        failureThreshold: 3
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 4
      targetCPUUtilizationPercentage: 70
    ingress:
      enabled: false
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls:
        enabled: true
        secretName: ""
    serviceAccount:
      create: true
      name: ""
      annotations: {}
    env: []
    envJson: "[{\"name\":\"SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE\",\"value\":\"5\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE\",\"value\":\"0\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT\",\"value\":\"30000\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_VALIDATION_TIMEOUT\",\"value\":\"5000\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT\",\"value\":\"30000\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_MAX_LIFETIME\",\"value\":\"45000\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_KEEPALIVE_TIME\",\"value\":\"15000\",\"secret\":false},{\"name\":\"SERVER_PORT\",\"value\":\"8888\",\"secret\":false}]"
  - name: "eureka-server"
    framework: "springboot-gradle"
    serviceType: "internal"
    exposePublic: false
    primaryPublic: false
    syncWave: 1
    replicaCount: 1
    containerPort: 8761
    servicePort: 8761
    host: "eureka-server-808e64-5e2adcb5.autonomous-istad.com"
    image:
      repository: "goharbor-itp.anajak-khmer.site/microservices-deployment/28cdfd36-7ffe-4491-83f3-0e44be/simple-micro/eureka-server"
      tag: "20-e54233756237"
      pullPolicy: "IfNotPresent"
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    probes:
      mode: "http"
      startup:
        enabled: true
        path: "/actuator/health"
        initialDelaySeconds: 0
        periodSeconds: 5
        failureThreshold: 24
      readiness:
        enabled: true
        path: "/actuator/health/readiness"
        initialDelaySeconds: 10
        periodSeconds: 10
        failureThreshold: 3
      liveness:
        enabled: true
        path: "/actuator/health/liveness"
        initialDelaySeconds: 30
        periodSeconds: 15
        failureThreshold: 3
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 4
      targetCPUUtilizationPercentage: 70
    ingress:
      enabled: false
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls:
        enabled: true
        secretName: ""
    serviceAccount:
      create: true
      name: ""
      annotations: {}
    env: []
    envJson: "[{\"name\":\"CONFIG_SERVER_URL\",\"value\":\"http://simple-micro-config-server.ns-sorn-sophamarinet-5e2adcb5.svc:8888/\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE\",\"value\":\"5\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE\",\"value\":\"0\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT\",\"value\":\"30000\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_VALIDATION_TIMEOUT\",\"value\":\"5000\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT\",\"value\":\"30000\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_MAX_LIFETIME\",\"value\":\"45000\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_KEEPALIVE_TIME\",\"value\":\"15000\",\"secret\":false},{\"name\":\"SERVER_PORT\",\"value\":\"8761\",\"secret\":false},{\"name\":\"EUREKA_INSTANCE_HOSTNAME\",\"value\":\"localhost\",\"secret\":false},{\"name\":\"SPRING_CONFIG_IMPORT\",\"value\":\"optional:configserver:http://simple-micro-config-server.ns-sorn-sophamarinet-5e2adcb5.svc:8888/\",\"secret\":false}]"
    dependsOn:
      - "config-server"
  - name: "category-service"
    framework: "springboot-gradle"
    serviceType: "internal"
    exposePublic: false
    primaryPublic: false
    syncWave: 2
    replicaCount: 1
    containerPort: 8484
    servicePort: 8484
    host: "category-service-808e64-5e2adcb5.autonomous-istad.com"
    image:
      repository: "goharbor-itp.anajak-khmer.site/microservices-deployment/28cdfd36-7ffe-4491-83f3-0e44be/simple-micro/category-service"
      tag: "20-e54233756237"
      pullPolicy: "IfNotPresent"
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    probes:
      mode: "http"
      startup:
        enabled: true
        path: "/actuator/health"
        initialDelaySeconds: 0
        periodSeconds: 5
        failureThreshold: 24
      readiness:
        enabled: true
        path: "/actuator/health/readiness"
        initialDelaySeconds: 10
        periodSeconds: 10
        failureThreshold: 3
      liveness:
        enabled: true
        path: "/actuator/health/liveness"
        initialDelaySeconds: 30
        periodSeconds: 15
        failureThreshold: 3
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 4
      targetCPUUtilizationPercentage: 70
    ingress:
      enabled: false
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls:
        enabled: true
        secretName: ""
    serviceAccount:
      create: true
      name: ""
      annotations: {}
    env: []
    envJson: "[{\"name\":\"CONFIG_SERVER_URL\",\"value\":\"http://simple-micro-config-server.ns-sorn-sophamarinet-5e2adcb5.svc:8888/\",\"secret\":false},{\"name\":\"EUREKA_SERVER_URL\",\"value\":\"http://simple-micro-eureka-server.ns-sorn-sophamarinet-5e2adcb5.svc:8761/eureka/\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE\",\"value\":\"5\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE\",\"value\":\"0\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT\",\"value\":\"30000\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_VALIDATION_TIMEOUT\",\"value\":\"5000\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT\",\"value\":\"30000\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_MAX_LIFETIME\",\"value\":\"45000\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_KEEPALIVE_TIME\",\"value\":\"15000\",\"secret\":false},{\"name\":\"SERVER_PORT\",\"value\":\"8484\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_URL\",\"value\":\"jdbc:postgresql://db-postgres-pg-7907d012.db.autonomous-istad.com:15433/postdb?sslmode=require\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_USERNAME\",\"value\":\"app_postgres\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_DRIVER_CLASS_NAME\",\"value\":\"org.postgresql.Driver\",\"secret\":false},{\"name\":\"APP_CORS_ALLOWED_ORIGIN_PATTERNS\",\"value\":\"*\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_PASSWORD\",\"value\":\"\",\"secret\":true},{\"name\":\"SPRING_CONFIG_IMPORT\",\"value\":\"optional:configserver:http://simple-micro-config-server.ns-sorn-sophamarinet-5e2adcb5.svc:8888/\",\"secret\":false},{\"name\":\"EUREKA_URL\",\"value\":\"http://simple-micro-eureka-server.ns-sorn-sophamarinet-5e2adcb5.svc:8761/eureka/\",\"secret\":false},{\"name\":\"EUREKA_CLIENT_SERVICEURL_DEFAULTZONE\",\"value\":\"http://simple-micro-eureka-server.ns-sorn-sophamarinet-5e2adcb5.svc:8761/eureka/\",\"secret\":false}]"
    dependsOn:
      - "config-server"
      - "eureka-server"
  - name: "product-service"
    framework: "springboot-gradle"
    serviceType: "internal"
    exposePublic: false
    primaryPublic: false
    syncWave: 2
    replicaCount: 1
    containerPort: 8081
    servicePort: 8081
    host: "product-service-808e64-5e2adcb5.autonomous-istad.com"
    image:
      repository: "goharbor-itp.anajak-khmer.site/microservices-deployment/28cdfd36-7ffe-4491-83f3-0e44be/simple-micro/product-service"
      tag: "21-073831722ffa"
      pullPolicy: "IfNotPresent"
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    probes:
      mode: "http"
      startup:
        enabled: true
        path: "/actuator/health"
        initialDelaySeconds: 0
        periodSeconds: 5
        failureThreshold: 24
      readiness:
        enabled: true
        path: "/actuator/health/readiness"
        initialDelaySeconds: 10
        periodSeconds: 10
        failureThreshold: 3
      liveness:
        enabled: true
        path: "/actuator/health/liveness"
        initialDelaySeconds: 30
        periodSeconds: 15
        failureThreshold: 3
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 4
      targetCPUUtilizationPercentage: 70
    ingress:
      enabled: false
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls:
        enabled: true
        secretName: ""
    serviceAccount:
      create: true
      name: ""
      annotations: {}
    env: []
    envJson: "[{\"name\":\"SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE\",\"value\":\"5\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE\",\"value\":\"0\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT\",\"value\":\"30000\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_VALIDATION_TIMEOUT\",\"value\":\"5000\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT\",\"value\":\"30000\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_MAX_LIFETIME\",\"value\":\"45000\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_KEEPALIVE_TIME\",\"value\":\"15000\",\"secret\":false},{\"name\":\"SERVER_PORT\",\"value\":\"8081\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_URL\",\"value\":\"jdbc:postgresql://db-postgres-pg-7907d012.db.autonomous-istad.com:15433/postdb?sslmode=require\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_USERNAME\",\"value\":\"app_postgres\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_DRIVER_CLASS_NAME\",\"value\":\"org.postgresql.Driver\",\"secret\":false},{\"name\":\"EUREKA_SERVER_URL\",\"value\":\"http://simple-micro-eureka-server.ns-sorn-sophamarinet-5e2adcb5.svc:8761/eureka/\",\"secret\":false},{\"name\":\"APP_CORS_ALLOWED_ORIGIN_PATTERNS\",\"value\":\"*\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_PASSWORD\",\"value\":\"\",\"secret\":true},{\"name\":\"CONFIG_SERVER_URL\",\"value\":\"http://simple-micro-config-server.ns-sorn-sophamarinet-5e2adcb5.svc:8888/\",\"secret\":false},{\"name\":\"SPRING_CONFIG_IMPORT\",\"value\":\"optional:configserver:http://simple-micro-config-server.ns-sorn-sophamarinet-5e2adcb5.svc:8888/\",\"secret\":false},{\"name\":\"EUREKA_URL\",\"value\":\"http://simple-micro-eureka-server.ns-sorn-sophamarinet-5e2adcb5.svc:8761/eureka/\",\"secret\":false},{\"name\":\"EUREKA_CLIENT_SERVICEURL_DEFAULTZONE\",\"value\":\"http://simple-micro-eureka-server.ns-sorn-sophamarinet-5e2adcb5.svc:8761/eureka/\",\"secret\":false}]"
    dependsOn:
      - "config-server"
      - "eureka-server"
  - name: "api-gateway"
    framework: "springboot-gradle"
    serviceType: "gateway"
    exposePublic: true
    primaryPublic: true
    syncWave: 3
    replicaCount: 1
    containerPort: 8282
    servicePort: 8282
    host: "marinet.shop"
    image:
      repository: "goharbor-itp.anajak-khmer.site/microservices-deployment/28cdfd36-7ffe-4491-83f3-0e44be/simple-micro/api-gateway"
      tag: "20-e54233756237"
      pullPolicy: "IfNotPresent"
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    probes:
      mode: "http"
      startup:
        enabled: true
        path: "/actuator/health"
        initialDelaySeconds: 0
        periodSeconds: 5
        failureThreshold: 24
      readiness:
        enabled: true
        path: "/actuator/health/readiness"
        initialDelaySeconds: 10
        periodSeconds: 10
        failureThreshold: 3
      liveness:
        enabled: true
        path: "/actuator/health/liveness"
        initialDelaySeconds: 30
        periodSeconds: 15
        failureThreshold: 3
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 4
      targetCPUUtilizationPercentage: 70
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls:
        enabled: true
        secretName: ""
    serviceAccount:
      create: true
      name: ""
      annotations: {}
    env: []
    envJson: "[{\"name\":\"CONFIG_SERVER_URL\",\"value\":\"http://simple-micro-config-server.ns-sorn-sophamarinet-5e2adcb5.svc:8888/\",\"secret\":false},{\"name\":\"EUREKA_SERVER_URL\",\"value\":\"http://simple-micro-eureka-server.ns-sorn-sophamarinet-5e2adcb5.svc:8761/eureka/\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE\",\"value\":\"5\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE\",\"value\":\"0\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT\",\"value\":\"30000\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_VALIDATION_TIMEOUT\",\"value\":\"5000\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT\",\"value\":\"30000\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_MAX_LIFETIME\",\"value\":\"45000\",\"secret\":false},{\"name\":\"SPRING_DATASOURCE_HIKARI_KEEPALIVE_TIME\",\"value\":\"15000\",\"secret\":false},{\"name\":\"SERVER_PORT\",\"value\":\"8282\",\"secret\":false},{\"name\":\"SPRING_CONFIG_IMPORT\",\"value\":\"optional:configserver:http://simple-micro-config-server.ns-sorn-sophamarinet-5e2adcb5.svc:8888/\",\"secret\":false},{\"name\":\"EUREKA_URL\",\"value\":\"http://simple-micro-eureka-server.ns-sorn-sophamarinet-5e2adcb5.svc:8761/eureka/\",\"secret\":false},{\"name\":\"EUREKA_CLIENT_SERVICEURL_DEFAULTZONE\",\"value\":\"http://simple-micro-eureka-server.ns-sorn-sophamarinet-5e2adcb5.svc:8761/eureka/\",\"secret\":false},{\"name\":\"UPSTREAM_BASE_URL\",\"value\":\"http://simple-micro-category-service.ns-sorn-sophamarinet-5e2adcb5.svc:8484/\",\"secret\":false},{\"name\":\"PRODUCT_SERVICE_URL\",\"value\":\"http://simple-micro-product-service.ns-sorn-sophamarinet-5e2adcb5.svc:8081/\",\"secret\":false},{\"name\":\"PRODUCT_SERVICE_BASE_URL\",\"value\":\"http://simple-micro-product-service.ns-sorn-sophamarinet-5e2adcb5.svc:8081/\",\"secret\":false},{\"name\":\"CATEGORY_SERVICE_URL\",\"value\":\"http://simple-micro-category-service.ns-sorn-sophamarinet-5e2adcb5.svc:8484/\",\"secret\":false},{\"name\":\"CATEGORY_SERVICE_BASE_URL\",\"value\":\"http://simple-micro-category-service.ns-sorn-sophamarinet-5e2adcb5.svc:8484/\",\"secret\":false}]"
    dependsOn:
      - "config-server"
      - "eureka-server"
