apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "test-shop-8737e41a-8b74-4136-aa2b-1bd8cf"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/managed-by: argocd
    platform.devops/project-name: "test-shop"
spec:
  project: "default"
  destination:
    server: https://kubernetes.default.svc
    namespace: "ns-porkeat-c18c6214"
  source:
    repoURL: "https://github.com/Vuthy-Tourn/platform-gitops"
    targetRevision: "main"
    path: "apps/ns-porkeat-c18c6214/8737e41a-8b74-4136-aa2b-1bd8cf/test-shop"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  info:
    - name: templateRepo
      value: "https://github.com/Vuthy-Tourn/platform-infra-testing"
    - name: templateRevision
      value: "main"
    - name: templatePath
      value: "helm/app-template"
