apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ns-porkeat-c18c6214
resources:
  - namespace.yaml
helmGlobals:
  chartHome: ../../../../templates/charts
helmCharts:
  - name: app-template
    releaseName: flower-shop-demo
    valuesFile: values.yaml
