apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ns-porkeat-c18c6214
helmGlobals:
  chartHome: ../../../../templates/charts
helmCharts:
  - name: app-template
    releaseName: test-shop
    valuesFile: values.yaml
