apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "simple-micro-28cdfd36-7ffe-4491-83f3-0e44be"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/managed-by: argocd
    platform.devops/project-name: "simple-micro"
spec:
  project: "default"
  destination:
    server: https://kubernetes.default.svc
    namespace: "ns-sorn-sophamarinet-5e2adcb5"
  source:
    repoURL: "https://github.com/Vuthy-Tourn/platform-gitops"
    targetRevision: "main"
    path: "apps/ns-sorn-sophamarinet-5e2adcb5/28cdfd36-7ffe-4491-83f3-0e44be/simple-micro"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  info:
    - name: templateRepo
      value: "https://github.com/Vuthy-Tourn/platform-infra-testing"
    - name: templateRevision
      value: "main"
    - name: templatePath
      value: "helm/app-template"
