workspace:
  id: "ns-vuthy-tourn-bba33c3e"
  userId: "980e1422-161f-4287-994e-101976"
  namespace: "ns-vuthy-tourn-bba33c3e"
  domain: "autonomous-istad.com"

imagePullSecrets:
  - name: "registry-secret"

defaults:
  replicaCount: 1
  image:
    pullPolicy: "IfNotPresent"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 70
  nodeSelector: {}
  tolerations: []
  affinity: {}

services:
  - name: "flower-eureka-server"
    framework: "springboot-gradle"
    serviceType: "internal"
    exposePublic: false
    primaryPublic: false
    syncWave: 0
    replicaCount: 1
    containerPort: 8761
    servicePort: 8761
    host: "multi-repo-flower-eureka-server-ns-vuthy-tourn-bba33c3e.autonomous-istad.com"
    image:
      repository: "harbor.devith.it.com/microservices-deployment/980e1422-161f-4287-994e-101976/flower-eureka-server"
      tag: "72-32ceddfb6c1a"
      pullPolicy: "IfNotPresent"
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    probes:
      mode: "tcp"
      startup:
        enabled: true
        initialDelaySeconds: 0
        periodSeconds: 5
        failureThreshold: 24
      readiness:
        enabled: true
        path: "/"
        initialDelaySeconds: 10
        periodSeconds: 10
        failureThreshold: 3
      liveness:
        enabled: true
        path: "/"
        initialDelaySeconds: 30
        periodSeconds: 15
        failureThreshold: 3
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 4
      targetCPUUtilizationPercentage: 70
    ingress:
      enabled: false
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls:
        enabled: true
        secretName: ""
    serviceAccount:
      create: true
      name: ""
      annotations: {}
    env: []
    envJson: "[]"
  - name: "flower-config-server"
    framework: "springboot-gradle"
    serviceType: "internal"
    exposePublic: false
    primaryPublic: false
    syncWave: 1
    replicaCount: 1
    containerPort: 8089
    servicePort: 8089
    host: "multi-repo-flower-config-server-ns-vuthy-tourn-bba33c3e.autonomous-istad.com"
    image:
      repository: "harbor.devith.it.com/microservices-deployment/980e1422-161f-4287-994e-101976/flower-config-server"
      tag: "72-52c0871f548d"
      pullPolicy: "IfNotPresent"
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    probes:
      mode: "tcp"
      startup:
        enabled: true
        initialDelaySeconds: 0
        periodSeconds: 5
        failureThreshold: 24
      readiness:
        enabled: true
        path: "/"
        initialDelaySeconds: 10
        periodSeconds: 10
        failureThreshold: 3
      liveness:
        enabled: true
        path: "/"
        initialDelaySeconds: 30
        periodSeconds: 15
        failureThreshold: 3
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 4
      targetCPUUtilizationPercentage: 70
    ingress:
      enabled: false
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls:
        enabled: true
        secretName: ""
    serviceAccount:
      create: true
      name: ""
      annotations: {}
    env: []
    envJson: "[{\"name\":\"EUREKA_URL\",\"value\":\"http://multi-repo-flower-eureka-server.ns-vuthy-tourn-bba33c3e.svc:8761/eureka/\"}]"
  - name: "flower-gateway-server"
    framework: "springboot-gradle"
    serviceType: "gateway"
    exposePublic: false
    primaryPublic: false
    syncWave: 2
    replicaCount: 1
    containerPort: 9099
    servicePort: 9099
    host: "multi-repo-flower-gateway-server-ns-vuthy-tourn-bba33c3e.autonomous-istad.com"
    image:
      repository: "harbor.devith.it.com/microservices-deployment/980e1422-161f-4287-994e-101976/flower-gateway-server"
      tag: "72-724dea343c93"
      pullPolicy: "IfNotPresent"
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    probes:
      mode: "tcp"
      startup:
        enabled: true
        initialDelaySeconds: 0
        periodSeconds: 5
        failureThreshold: 24
      readiness:
        enabled: true
        path: "/"
        initialDelaySeconds: 10
        periodSeconds: 10
        failureThreshold: 3
      liveness:
        enabled: true
        path: "/"
        initialDelaySeconds: 30
        periodSeconds: 15
        failureThreshold: 3
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 4
      targetCPUUtilizationPercentage: 70
    ingress:
      enabled: false
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls:
        enabled: true
        secretName: ""
    serviceAccount:
      create: true
      name: ""
      annotations: {}
    env: []
    envJson: "[{\"name\":\"CONFIG_SERVER_URL\",\"value\":\"http://multi-repo-flower-config-server.ns-vuthy-tourn-bba33c3e.svc:8089/\"},{\"name\":\"EUREKA_URL\",\"value\":\"http://multi-repo-flower-eureka-server.ns-vuthy-tourn-bba33c3e.svc:8761/eureka/\"}]"
