apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ns-vuthy-tourn-f464566f
helmGlobals:
  chartHome: ../../../../templates/charts
helmCharts:
  - name: app-template
    releaseName: tui-test
    valuesFile: values.yaml
