apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "flower-122d1924-4c05-41d4-878d-57293d"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/managed-by: argocd
    platform.devops/project-name: "flower"
spec:
  project: "default"
  destination:
    server: https://kubernetes.default.svc
    namespace: "ns-sorn-sophamarinet-c2332eff"
  source:
    repoURL: "https://github.com/Vuthy-Tourn/platform-gitops"
    targetRevision: "main"
    path: "apps/ns-sorn-sophamarinet-c2332eff/122d1924-4c05-41d4-878d-57293d/flower"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  info:
    - name: templateRepo
      value: "https://github.com/Vuthy-Tourn/platform-infra-testing"
    - name: templateRevision
      value: "main"
    - name: templatePath
      value: "helm/app-template"
